# Makefile para compilar e executar o código

# Comando de compilação
all: main.c stack_queues.c
	gcc -o main main.c stack_queues.c

# Comando de execução
run: all
	./main

# Limpeza de arquivos temporários
clean:
	rm -f main
