# Makefile para compilar e executar o código

# Comando de compilação
all: main.c contact_list.c
	gcc -o main main.c contact_list.c

# Comando de execução
run: all
	./main

# Limpeza de arquivos temporários
clean:
	rm -f main
